language: php

php:
  - 5.6
  - 7.0
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

env:
  - DB=pgsql
  - DB=mysql

sudo: false

services:
  - mysql
  - postgresql

addons:
  postgresql: 9.4

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source
  - sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'create database db_tests;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'create database IF NOT EXISTS db_tests;'; fi"

script: ./vendor/bin/tester -p php -c ./tests/php-unix.ini ./tests/DbTests

cache:
  directories:
    - $HOME/.composer/cache
